### ISSUE TITLE
How to add a placeholder to the contenteditable div

### ISSUE THREAD

**Issue by mohanzeal** [PeakTai/vue-html5-editor#100]
I want to show a placeholder to the content section. How is this acheived?

A quick google search brought me a css fix but how should I apply this.

```
[contenteditable=true]:empty:before {
  content: attr(placeholder);
  width: inherit;
  height: inherit;
  color: grey;
  display: block;
}
```

**Comment by ryantbrown** [comment]
I just did this - put the following in your css somewhere:

```css
.vue-html5-editor [contenteditable=true]:empty:before {
  content: attr(placeholder);
  width: inherit;
  height: inherit;
  color: grey;
  display: block;
}
```

And then the following in the `.vue` component that uses `vue-html5-editor`:

```js
const html5 = document.querySelector('.vue-html5-editor .content');
html5.setAttribute('placeholder', 'Your placeholder here');
```

You cannot put the placeholder as an attribute on the component because it does not pass it down the actual `.content` div.
